// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: VoiceVerificationMessage.proto

#include "VoiceVerificationMessage.pb.h"
#include "VoiceVerificationMessage.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>

static const char* VerificationMsgService_method_names[] = {
  "/VerificationMsgService/verificationVoice",
};

std::unique_ptr< VerificationMsgService::Stub> VerificationMsgService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< VerificationMsgService::Stub> stub(new VerificationMsgService::Stub(channel, options));
  return stub;
}

VerificationMsgService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_verificationVoice_(VerificationMsgService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status VerificationMsgService::Stub::verificationVoice(::grpc::ClientContext* context, const ::VoiceVerificationRequestMsg& request, ::VoiceVerificationResponseMsg* response) {
  return ::grpc::internal::BlockingUnaryCall< ::VoiceVerificationRequestMsg, ::VoiceVerificationResponseMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_verificationVoice_, context, request, response);
}

void VerificationMsgService::Stub::experimental_async::verificationVoice(::grpc::ClientContext* context, const ::VoiceVerificationRequestMsg* request, ::VoiceVerificationResponseMsg* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::VoiceVerificationRequestMsg, ::VoiceVerificationResponseMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_verificationVoice_, context, request, response, std::move(f));
}

void VerificationMsgService::Stub::experimental_async::verificationVoice(::grpc::ClientContext* context, const ::VoiceVerificationRequestMsg* request, ::VoiceVerificationResponseMsg* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_verificationVoice_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::VoiceVerificationResponseMsg>* VerificationMsgService::Stub::PrepareAsyncverificationVoiceRaw(::grpc::ClientContext* context, const ::VoiceVerificationRequestMsg& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::VoiceVerificationResponseMsg, ::VoiceVerificationRequestMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_verificationVoice_, context, request);
}

::grpc::ClientAsyncResponseReader< ::VoiceVerificationResponseMsg>* VerificationMsgService::Stub::AsyncverificationVoiceRaw(::grpc::ClientContext* context, const ::VoiceVerificationRequestMsg& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncverificationVoiceRaw(context, request, cq);
  result->StartCall();
  return result;
}

VerificationMsgService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      VerificationMsgService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< VerificationMsgService::Service, ::VoiceVerificationRequestMsg, ::VoiceVerificationResponseMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](VerificationMsgService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::VoiceVerificationRequestMsg* req,
             ::VoiceVerificationResponseMsg* resp) {
               return service->verificationVoice(ctx, req, resp);
             }, this)));
}

VerificationMsgService::Service::~Service() {
}

::grpc::Status VerificationMsgService::Service::verificationVoice(::grpc::ServerContext* context, const ::VoiceVerificationRequestMsg* request, ::VoiceVerificationResponseMsg* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


