// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: VoiceVerificationMessage.proto

#include "VoiceVerificationMessage.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
constexpr VoiceVerificationRequestMsg::VoiceVerificationRequestMsg(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : path_file_verify_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , path_file_trained_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , options_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string){}
struct VoiceVerificationRequestMsgDefaultTypeInternal {
  constexpr VoiceVerificationRequestMsgDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~VoiceVerificationRequestMsgDefaultTypeInternal() {}
  union {
    VoiceVerificationRequestMsg _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT VoiceVerificationRequestMsgDefaultTypeInternal _VoiceVerificationRequestMsg_default_instance_;
constexpr VoiceVerificationResponseMsg::VoiceVerificationResponseMsg(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : additionalinfo_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , errorcode_(0)
  , score_(0){}
struct VoiceVerificationResponseMsgDefaultTypeInternal {
  constexpr VoiceVerificationResponseMsgDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~VoiceVerificationResponseMsgDefaultTypeInternal() {}
  union {
    VoiceVerificationResponseMsg _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT VoiceVerificationResponseMsgDefaultTypeInternal _VoiceVerificationResponseMsg_default_instance_;
static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_VoiceVerificationMessage_2eproto[2];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_VoiceVerificationMessage_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_VoiceVerificationMessage_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_VoiceVerificationMessage_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::VoiceVerificationRequestMsg, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::VoiceVerificationRequestMsg, path_file_verify_),
  PROTOBUF_FIELD_OFFSET(::VoiceVerificationRequestMsg, path_file_trained_),
  PROTOBUF_FIELD_OFFSET(::VoiceVerificationRequestMsg, options_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::VoiceVerificationResponseMsg, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::VoiceVerificationResponseMsg, errorcode_),
  PROTOBUF_FIELD_OFFSET(::VoiceVerificationResponseMsg, score_),
  PROTOBUF_FIELD_OFFSET(::VoiceVerificationResponseMsg, additionalinfo_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::VoiceVerificationRequestMsg)},
  { 8, -1, sizeof(::VoiceVerificationResponseMsg)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::_VoiceVerificationRequestMsg_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::_VoiceVerificationResponseMsg_default_instance_),
};

const char descriptor_table_protodef_VoiceVerificationMessage_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\036VoiceVerificationMessage.proto\"c\n\033Voic"
  "eVerificationRequestMsg\022\030\n\020path_file_ver"
  "ify\030\001 \001(\t\022\031\n\021path_file_trained\030\002 \001(\t\022\017\n\007"
  "options\030\003 \001(\t\"X\n\034VoiceVerificationRespon"
  "seMsg\022\021\n\terrorcode\030\001 \001(\005\022\r\n\005score\030\002 \001(\002\022"
  "\026\n\016additionalInfo\030\003 \001(\t2l\n\026VerificationM"
  "sgService\022R\n\021verificationVoice\022\034.VoiceVe"
  "rificationRequestMsg\032\035.VoiceVerification"
  "ResponseMsg\"\000B>\n com.vnptpay.voiceverify"
  ".messagesB\030VoiceVerificationMessageP\001b\006p"
  "roto3"
  ;
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_VoiceVerificationMessage_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_VoiceVerificationMessage_2eproto = {
  false, false, 405, descriptor_table_protodef_VoiceVerificationMessage_2eproto, "VoiceVerificationMessage.proto", 
  &descriptor_table_VoiceVerificationMessage_2eproto_once, nullptr, 0, 2,
  schemas, file_default_instances, TableStruct_VoiceVerificationMessage_2eproto::offsets,
  file_level_metadata_VoiceVerificationMessage_2eproto, file_level_enum_descriptors_VoiceVerificationMessage_2eproto, file_level_service_descriptors_VoiceVerificationMessage_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK ::PROTOBUF_NAMESPACE_ID::Metadata
descriptor_table_VoiceVerificationMessage_2eproto_metadata_getter(int index) {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_VoiceVerificationMessage_2eproto);
  return descriptor_table_VoiceVerificationMessage_2eproto.file_level_metadata[index];
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_VoiceVerificationMessage_2eproto(&descriptor_table_VoiceVerificationMessage_2eproto);

// ===================================================================

class VoiceVerificationRequestMsg::_Internal {
 public:
};

VoiceVerificationRequestMsg::VoiceVerificationRequestMsg(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:VoiceVerificationRequestMsg)
}
VoiceVerificationRequestMsg::VoiceVerificationRequestMsg(const VoiceVerificationRequestMsg& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  path_file_verify_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_path_file_verify().empty()) {
    path_file_verify_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_path_file_verify(), 
      GetArena());
  }
  path_file_trained_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_path_file_trained().empty()) {
    path_file_trained_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_path_file_trained(), 
      GetArena());
  }
  options_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_options().empty()) {
    options_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_options(), 
      GetArena());
  }
  // @@protoc_insertion_point(copy_constructor:VoiceVerificationRequestMsg)
}

void VoiceVerificationRequestMsg::SharedCtor() {
path_file_verify_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
path_file_trained_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
options_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

VoiceVerificationRequestMsg::~VoiceVerificationRequestMsg() {
  // @@protoc_insertion_point(destructor:VoiceVerificationRequestMsg)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void VoiceVerificationRequestMsg::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  path_file_verify_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  path_file_trained_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  options_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void VoiceVerificationRequestMsg::ArenaDtor(void* object) {
  VoiceVerificationRequestMsg* _this = reinterpret_cast< VoiceVerificationRequestMsg* >(object);
  (void)_this;
}
void VoiceVerificationRequestMsg::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void VoiceVerificationRequestMsg::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void VoiceVerificationRequestMsg::Clear() {
// @@protoc_insertion_point(message_clear_start:VoiceVerificationRequestMsg)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  path_file_verify_.ClearToEmpty();
  path_file_trained_.ClearToEmpty();
  options_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* VoiceVerificationRequestMsg::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // string path_file_verify = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_path_file_verify();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "VoiceVerificationRequestMsg.path_file_verify"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string path_file_trained = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          auto str = _internal_mutable_path_file_trained();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "VoiceVerificationRequestMsg.path_file_trained"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string options = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          auto str = _internal_mutable_options();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "VoiceVerificationRequestMsg.options"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* VoiceVerificationRequestMsg::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:VoiceVerificationRequestMsg)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string path_file_verify = 1;
  if (this->path_file_verify().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_path_file_verify().data(), static_cast<int>(this->_internal_path_file_verify().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "VoiceVerificationRequestMsg.path_file_verify");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_path_file_verify(), target);
  }

  // string path_file_trained = 2;
  if (this->path_file_trained().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_path_file_trained().data(), static_cast<int>(this->_internal_path_file_trained().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "VoiceVerificationRequestMsg.path_file_trained");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_path_file_trained(), target);
  }

  // string options = 3;
  if (this->options().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_options().data(), static_cast<int>(this->_internal_options().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "VoiceVerificationRequestMsg.options");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_options(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:VoiceVerificationRequestMsg)
  return target;
}

size_t VoiceVerificationRequestMsg::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:VoiceVerificationRequestMsg)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string path_file_verify = 1;
  if (this->path_file_verify().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_path_file_verify());
  }

  // string path_file_trained = 2;
  if (this->path_file_trained().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_path_file_trained());
  }

  // string options = 3;
  if (this->options().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_options());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void VoiceVerificationRequestMsg::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:VoiceVerificationRequestMsg)
  GOOGLE_DCHECK_NE(&from, this);
  const VoiceVerificationRequestMsg* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<VoiceVerificationRequestMsg>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:VoiceVerificationRequestMsg)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:VoiceVerificationRequestMsg)
    MergeFrom(*source);
  }
}

void VoiceVerificationRequestMsg::MergeFrom(const VoiceVerificationRequestMsg& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:VoiceVerificationRequestMsg)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.path_file_verify().size() > 0) {
    _internal_set_path_file_verify(from._internal_path_file_verify());
  }
  if (from.path_file_trained().size() > 0) {
    _internal_set_path_file_trained(from._internal_path_file_trained());
  }
  if (from.options().size() > 0) {
    _internal_set_options(from._internal_options());
  }
}

void VoiceVerificationRequestMsg::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:VoiceVerificationRequestMsg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void VoiceVerificationRequestMsg::CopyFrom(const VoiceVerificationRequestMsg& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:VoiceVerificationRequestMsg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool VoiceVerificationRequestMsg::IsInitialized() const {
  return true;
}

void VoiceVerificationRequestMsg::InternalSwap(VoiceVerificationRequestMsg* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  path_file_verify_.Swap(&other->path_file_verify_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  path_file_trained_.Swap(&other->path_file_trained_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  options_.Swap(&other->options_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}

::PROTOBUF_NAMESPACE_ID::Metadata VoiceVerificationRequestMsg::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

class VoiceVerificationResponseMsg::_Internal {
 public:
};

VoiceVerificationResponseMsg::VoiceVerificationResponseMsg(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:VoiceVerificationResponseMsg)
}
VoiceVerificationResponseMsg::VoiceVerificationResponseMsg(const VoiceVerificationResponseMsg& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  additionalinfo_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_additionalinfo().empty()) {
    additionalinfo_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_additionalinfo(), 
      GetArena());
  }
  ::memcpy(&errorcode_, &from.errorcode_,
    static_cast<size_t>(reinterpret_cast<char*>(&score_) -
    reinterpret_cast<char*>(&errorcode_)) + sizeof(score_));
  // @@protoc_insertion_point(copy_constructor:VoiceVerificationResponseMsg)
}

void VoiceVerificationResponseMsg::SharedCtor() {
additionalinfo_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
    reinterpret_cast<char*>(&errorcode_) - reinterpret_cast<char*>(this)),
    0, static_cast<size_t>(reinterpret_cast<char*>(&score_) -
    reinterpret_cast<char*>(&errorcode_)) + sizeof(score_));
}

VoiceVerificationResponseMsg::~VoiceVerificationResponseMsg() {
  // @@protoc_insertion_point(destructor:VoiceVerificationResponseMsg)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void VoiceVerificationResponseMsg::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  additionalinfo_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void VoiceVerificationResponseMsg::ArenaDtor(void* object) {
  VoiceVerificationResponseMsg* _this = reinterpret_cast< VoiceVerificationResponseMsg* >(object);
  (void)_this;
}
void VoiceVerificationResponseMsg::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void VoiceVerificationResponseMsg::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void VoiceVerificationResponseMsg::Clear() {
// @@protoc_insertion_point(message_clear_start:VoiceVerificationResponseMsg)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  additionalinfo_.ClearToEmpty();
  ::memset(&errorcode_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&score_) -
      reinterpret_cast<char*>(&errorcode_)) + sizeof(score_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* VoiceVerificationResponseMsg::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // int32 errorcode = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          errorcode_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // float score = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 21)) {
          score_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // string additionalInfo = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          auto str = _internal_mutable_additionalinfo();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "VoiceVerificationResponseMsg.additionalInfo"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* VoiceVerificationResponseMsg::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:VoiceVerificationResponseMsg)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 errorcode = 1;
  if (this->errorcode() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(1, this->_internal_errorcode(), target);
  }

  // float score = 2;
  if (!(this->score() <= 0 && this->score() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(2, this->_internal_score(), target);
  }

  // string additionalInfo = 3;
  if (this->additionalinfo().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_additionalinfo().data(), static_cast<int>(this->_internal_additionalinfo().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "VoiceVerificationResponseMsg.additionalInfo");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_additionalinfo(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:VoiceVerificationResponseMsg)
  return target;
}

size_t VoiceVerificationResponseMsg::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:VoiceVerificationResponseMsg)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string additionalInfo = 3;
  if (this->additionalinfo().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_additionalinfo());
  }

  // int32 errorcode = 1;
  if (this->errorcode() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_errorcode());
  }

  // float score = 2;
  if (!(this->score() <= 0 && this->score() >= 0)) {
    total_size += 1 + 4;
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void VoiceVerificationResponseMsg::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:VoiceVerificationResponseMsg)
  GOOGLE_DCHECK_NE(&from, this);
  const VoiceVerificationResponseMsg* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<VoiceVerificationResponseMsg>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:VoiceVerificationResponseMsg)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:VoiceVerificationResponseMsg)
    MergeFrom(*source);
  }
}

void VoiceVerificationResponseMsg::MergeFrom(const VoiceVerificationResponseMsg& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:VoiceVerificationResponseMsg)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.additionalinfo().size() > 0) {
    _internal_set_additionalinfo(from._internal_additionalinfo());
  }
  if (from.errorcode() != 0) {
    _internal_set_errorcode(from._internal_errorcode());
  }
  if (!(from.score() <= 0 && from.score() >= 0)) {
    _internal_set_score(from._internal_score());
  }
}

void VoiceVerificationResponseMsg::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:VoiceVerificationResponseMsg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void VoiceVerificationResponseMsg::CopyFrom(const VoiceVerificationResponseMsg& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:VoiceVerificationResponseMsg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool VoiceVerificationResponseMsg::IsInitialized() const {
  return true;
}

void VoiceVerificationResponseMsg::InternalSwap(VoiceVerificationResponseMsg* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  additionalinfo_.Swap(&other->additionalinfo_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(VoiceVerificationResponseMsg, score_)
      + sizeof(VoiceVerificationResponseMsg::score_)
      - PROTOBUF_FIELD_OFFSET(VoiceVerificationResponseMsg, errorcode_)>(
          reinterpret_cast<char*>(&errorcode_),
          reinterpret_cast<char*>(&other->errorcode_));
}

::PROTOBUF_NAMESPACE_ID::Metadata VoiceVerificationResponseMsg::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::VoiceVerificationRequestMsg* Arena::CreateMaybeMessage< ::VoiceVerificationRequestMsg >(Arena* arena) {
  return Arena::CreateMessageInternal< ::VoiceVerificationRequestMsg >(arena);
}
template<> PROTOBUF_NOINLINE ::VoiceVerificationResponseMsg* Arena::CreateMaybeMessage< ::VoiceVerificationResponseMsg >(Arena* arena) {
  return Arena::CreateMessageInternal< ::VoiceVerificationResponseMsg >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
