// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: VoiceRegisterMessage.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_VoiceRegisterMessage_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_VoiceRegisterMessage_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3015000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3015008 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_VoiceRegisterMessage_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_VoiceRegisterMessage_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[2]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_VoiceRegisterMessage_2eproto;
::PROTOBUF_NAMESPACE_ID::Metadata descriptor_table_VoiceRegisterMessage_2eproto_metadata_getter(int index);
class VoiceRegisterRequestMsg;
struct VoiceRegisterRequestMsgDefaultTypeInternal;
extern VoiceRegisterRequestMsgDefaultTypeInternal _VoiceRegisterRequestMsg_default_instance_;
class VoiceRegisterResponseMsg;
struct VoiceRegisterResponseMsgDefaultTypeInternal;
extern VoiceRegisterResponseMsgDefaultTypeInternal _VoiceRegisterResponseMsg_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::VoiceRegisterRequestMsg* Arena::CreateMaybeMessage<::VoiceRegisterRequestMsg>(Arena*);
template<> ::VoiceRegisterResponseMsg* Arena::CreateMaybeMessage<::VoiceRegisterResponseMsg>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class VoiceRegisterRequestMsg PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:VoiceRegisterRequestMsg) */ {
 public:
  inline VoiceRegisterRequestMsg() : VoiceRegisterRequestMsg(nullptr) {}
  virtual ~VoiceRegisterRequestMsg();
  explicit constexpr VoiceRegisterRequestMsg(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  VoiceRegisterRequestMsg(const VoiceRegisterRequestMsg& from);
  VoiceRegisterRequestMsg(VoiceRegisterRequestMsg&& from) noexcept
    : VoiceRegisterRequestMsg() {
    *this = ::std::move(from);
  }

  inline VoiceRegisterRequestMsg& operator=(const VoiceRegisterRequestMsg& from) {
    CopyFrom(from);
    return *this;
  }
  inline VoiceRegisterRequestMsg& operator=(VoiceRegisterRequestMsg&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const VoiceRegisterRequestMsg& default_instance() {
    return *internal_default_instance();
  }
  static inline const VoiceRegisterRequestMsg* internal_default_instance() {
    return reinterpret_cast<const VoiceRegisterRequestMsg*>(
               &_VoiceRegisterRequestMsg_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(VoiceRegisterRequestMsg& a, VoiceRegisterRequestMsg& b) {
    a.Swap(&b);
  }
  inline void Swap(VoiceRegisterRequestMsg* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(VoiceRegisterRequestMsg* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline VoiceRegisterRequestMsg* New() const final {
    return CreateMaybeMessage<VoiceRegisterRequestMsg>(nullptr);
  }

  VoiceRegisterRequestMsg* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<VoiceRegisterRequestMsg>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const VoiceRegisterRequestMsg& from);
  void MergeFrom(const VoiceRegisterRequestMsg& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(VoiceRegisterRequestMsg* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "VoiceRegisterRequestMsg";
  }
  protected:
  explicit VoiceRegisterRequestMsg(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    return ::descriptor_table_VoiceRegisterMessage_2eproto_metadata_getter(kIndexInFileMessages);
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPathFileFieldNumber = 1,
    kOptionsFieldNumber = 3,
    kTypeFieldNumber = 2,
  };
  // string path_file = 1;
  void clear_path_file();
  const std::string& path_file() const;
  void set_path_file(const std::string& value);
  void set_path_file(std::string&& value);
  void set_path_file(const char* value);
  void set_path_file(const char* value, size_t size);
  std::string* mutable_path_file();
  std::string* release_path_file();
  void set_allocated_path_file(std::string* path_file);
  private:
  const std::string& _internal_path_file() const;
  void _internal_set_path_file(const std::string& value);
  std::string* _internal_mutable_path_file();
  public:

  // string options = 3;
  void clear_options();
  const std::string& options() const;
  void set_options(const std::string& value);
  void set_options(std::string&& value);
  void set_options(const char* value);
  void set_options(const char* value, size_t size);
  std::string* mutable_options();
  std::string* release_options();
  void set_allocated_options(std::string* options);
  private:
  const std::string& _internal_options() const;
  void _internal_set_options(const std::string& value);
  std::string* _internal_mutable_options();
  public:

  // int32 type = 2;
  void clear_type();
  ::PROTOBUF_NAMESPACE_ID::int32 type() const;
  void set_type(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_type() const;
  void _internal_set_type(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:VoiceRegisterRequestMsg)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr path_file_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr options_;
  ::PROTOBUF_NAMESPACE_ID::int32 type_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_VoiceRegisterMessage_2eproto;
};
// -------------------------------------------------------------------

class VoiceRegisterResponseMsg PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:VoiceRegisterResponseMsg) */ {
 public:
  inline VoiceRegisterResponseMsg() : VoiceRegisterResponseMsg(nullptr) {}
  virtual ~VoiceRegisterResponseMsg();
  explicit constexpr VoiceRegisterResponseMsg(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  VoiceRegisterResponseMsg(const VoiceRegisterResponseMsg& from);
  VoiceRegisterResponseMsg(VoiceRegisterResponseMsg&& from) noexcept
    : VoiceRegisterResponseMsg() {
    *this = ::std::move(from);
  }

  inline VoiceRegisterResponseMsg& operator=(const VoiceRegisterResponseMsg& from) {
    CopyFrom(from);
    return *this;
  }
  inline VoiceRegisterResponseMsg& operator=(VoiceRegisterResponseMsg&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const VoiceRegisterResponseMsg& default_instance() {
    return *internal_default_instance();
  }
  static inline const VoiceRegisterResponseMsg* internal_default_instance() {
    return reinterpret_cast<const VoiceRegisterResponseMsg*>(
               &_VoiceRegisterResponseMsg_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(VoiceRegisterResponseMsg& a, VoiceRegisterResponseMsg& b) {
    a.Swap(&b);
  }
  inline void Swap(VoiceRegisterResponseMsg* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(VoiceRegisterResponseMsg* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline VoiceRegisterResponseMsg* New() const final {
    return CreateMaybeMessage<VoiceRegisterResponseMsg>(nullptr);
  }

  VoiceRegisterResponseMsg* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<VoiceRegisterResponseMsg>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const VoiceRegisterResponseMsg& from);
  void MergeFrom(const VoiceRegisterResponseMsg& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(VoiceRegisterResponseMsg* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "VoiceRegisterResponseMsg";
  }
  protected:
  explicit VoiceRegisterResponseMsg(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    return ::descriptor_table_VoiceRegisterMessage_2eproto_metadata_getter(kIndexInFileMessages);
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kAdditionalInfoFieldNumber = 2,
    kErrorcodeFieldNumber = 1,
  };
  // string additionalInfo = 2;
  void clear_additionalinfo();
  const std::string& additionalinfo() const;
  void set_additionalinfo(const std::string& value);
  void set_additionalinfo(std::string&& value);
  void set_additionalinfo(const char* value);
  void set_additionalinfo(const char* value, size_t size);
  std::string* mutable_additionalinfo();
  std::string* release_additionalinfo();
  void set_allocated_additionalinfo(std::string* additionalinfo);
  private:
  const std::string& _internal_additionalinfo() const;
  void _internal_set_additionalinfo(const std::string& value);
  std::string* _internal_mutable_additionalinfo();
  public:

  // int32 errorcode = 1;
  void clear_errorcode();
  ::PROTOBUF_NAMESPACE_ID::int32 errorcode() const;
  void set_errorcode(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_errorcode() const;
  void _internal_set_errorcode(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:VoiceRegisterResponseMsg)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr additionalinfo_;
  ::PROTOBUF_NAMESPACE_ID::int32 errorcode_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_VoiceRegisterMessage_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// VoiceRegisterRequestMsg

// string path_file = 1;
inline void VoiceRegisterRequestMsg::clear_path_file() {
  path_file_.ClearToEmpty();
}
inline const std::string& VoiceRegisterRequestMsg::path_file() const {
  // @@protoc_insertion_point(field_get:VoiceRegisterRequestMsg.path_file)
  return _internal_path_file();
}
inline void VoiceRegisterRequestMsg::set_path_file(const std::string& value) {
  _internal_set_path_file(value);
  // @@protoc_insertion_point(field_set:VoiceRegisterRequestMsg.path_file)
}
inline std::string* VoiceRegisterRequestMsg::mutable_path_file() {
  // @@protoc_insertion_point(field_mutable:VoiceRegisterRequestMsg.path_file)
  return _internal_mutable_path_file();
}
inline const std::string& VoiceRegisterRequestMsg::_internal_path_file() const {
  return path_file_.Get();
}
inline void VoiceRegisterRequestMsg::_internal_set_path_file(const std::string& value) {
  
  path_file_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void VoiceRegisterRequestMsg::set_path_file(std::string&& value) {
  
  path_file_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:VoiceRegisterRequestMsg.path_file)
}
inline void VoiceRegisterRequestMsg::set_path_file(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  path_file_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:VoiceRegisterRequestMsg.path_file)
}
inline void VoiceRegisterRequestMsg::set_path_file(const char* value,
    size_t size) {
  
  path_file_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:VoiceRegisterRequestMsg.path_file)
}
inline std::string* VoiceRegisterRequestMsg::_internal_mutable_path_file() {
  
  return path_file_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* VoiceRegisterRequestMsg::release_path_file() {
  // @@protoc_insertion_point(field_release:VoiceRegisterRequestMsg.path_file)
  return path_file_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void VoiceRegisterRequestMsg::set_allocated_path_file(std::string* path_file) {
  if (path_file != nullptr) {
    
  } else {
    
  }
  path_file_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), path_file,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:VoiceRegisterRequestMsg.path_file)
}

// int32 type = 2;
inline void VoiceRegisterRequestMsg::clear_type() {
  type_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 VoiceRegisterRequestMsg::_internal_type() const {
  return type_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 VoiceRegisterRequestMsg::type() const {
  // @@protoc_insertion_point(field_get:VoiceRegisterRequestMsg.type)
  return _internal_type();
}
inline void VoiceRegisterRequestMsg::_internal_set_type(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  type_ = value;
}
inline void VoiceRegisterRequestMsg::set_type(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:VoiceRegisterRequestMsg.type)
}

// string options = 3;
inline void VoiceRegisterRequestMsg::clear_options() {
  options_.ClearToEmpty();
}
inline const std::string& VoiceRegisterRequestMsg::options() const {
  // @@protoc_insertion_point(field_get:VoiceRegisterRequestMsg.options)
  return _internal_options();
}
inline void VoiceRegisterRequestMsg::set_options(const std::string& value) {
  _internal_set_options(value);
  // @@protoc_insertion_point(field_set:VoiceRegisterRequestMsg.options)
}
inline std::string* VoiceRegisterRequestMsg::mutable_options() {
  // @@protoc_insertion_point(field_mutable:VoiceRegisterRequestMsg.options)
  return _internal_mutable_options();
}
inline const std::string& VoiceRegisterRequestMsg::_internal_options() const {
  return options_.Get();
}
inline void VoiceRegisterRequestMsg::_internal_set_options(const std::string& value) {
  
  options_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void VoiceRegisterRequestMsg::set_options(std::string&& value) {
  
  options_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:VoiceRegisterRequestMsg.options)
}
inline void VoiceRegisterRequestMsg::set_options(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  options_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:VoiceRegisterRequestMsg.options)
}
inline void VoiceRegisterRequestMsg::set_options(const char* value,
    size_t size) {
  
  options_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:VoiceRegisterRequestMsg.options)
}
inline std::string* VoiceRegisterRequestMsg::_internal_mutable_options() {
  
  return options_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* VoiceRegisterRequestMsg::release_options() {
  // @@protoc_insertion_point(field_release:VoiceRegisterRequestMsg.options)
  return options_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void VoiceRegisterRequestMsg::set_allocated_options(std::string* options) {
  if (options != nullptr) {
    
  } else {
    
  }
  options_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), options,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:VoiceRegisterRequestMsg.options)
}

// -------------------------------------------------------------------

// VoiceRegisterResponseMsg

// int32 errorcode = 1;
inline void VoiceRegisterResponseMsg::clear_errorcode() {
  errorcode_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 VoiceRegisterResponseMsg::_internal_errorcode() const {
  return errorcode_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 VoiceRegisterResponseMsg::errorcode() const {
  // @@protoc_insertion_point(field_get:VoiceRegisterResponseMsg.errorcode)
  return _internal_errorcode();
}
inline void VoiceRegisterResponseMsg::_internal_set_errorcode(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  errorcode_ = value;
}
inline void VoiceRegisterResponseMsg::set_errorcode(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_errorcode(value);
  // @@protoc_insertion_point(field_set:VoiceRegisterResponseMsg.errorcode)
}

// string additionalInfo = 2;
inline void VoiceRegisterResponseMsg::clear_additionalinfo() {
  additionalinfo_.ClearToEmpty();
}
inline const std::string& VoiceRegisterResponseMsg::additionalinfo() const {
  // @@protoc_insertion_point(field_get:VoiceRegisterResponseMsg.additionalInfo)
  return _internal_additionalinfo();
}
inline void VoiceRegisterResponseMsg::set_additionalinfo(const std::string& value) {
  _internal_set_additionalinfo(value);
  // @@protoc_insertion_point(field_set:VoiceRegisterResponseMsg.additionalInfo)
}
inline std::string* VoiceRegisterResponseMsg::mutable_additionalinfo() {
  // @@protoc_insertion_point(field_mutable:VoiceRegisterResponseMsg.additionalInfo)
  return _internal_mutable_additionalinfo();
}
inline const std::string& VoiceRegisterResponseMsg::_internal_additionalinfo() const {
  return additionalinfo_.Get();
}
inline void VoiceRegisterResponseMsg::_internal_set_additionalinfo(const std::string& value) {
  
  additionalinfo_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void VoiceRegisterResponseMsg::set_additionalinfo(std::string&& value) {
  
  additionalinfo_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:VoiceRegisterResponseMsg.additionalInfo)
}
inline void VoiceRegisterResponseMsg::set_additionalinfo(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  additionalinfo_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:VoiceRegisterResponseMsg.additionalInfo)
}
inline void VoiceRegisterResponseMsg::set_additionalinfo(const char* value,
    size_t size) {
  
  additionalinfo_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:VoiceRegisterResponseMsg.additionalInfo)
}
inline std::string* VoiceRegisterResponseMsg::_internal_mutable_additionalinfo() {
  
  return additionalinfo_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* VoiceRegisterResponseMsg::release_additionalinfo() {
  // @@protoc_insertion_point(field_release:VoiceRegisterResponseMsg.additionalInfo)
  return additionalinfo_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void VoiceRegisterResponseMsg::set_allocated_additionalinfo(std::string* additionalinfo) {
  if (additionalinfo != nullptr) {
    
  } else {
    
  }
  additionalinfo_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), additionalinfo,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:VoiceRegisterResponseMsg.additionalInfo)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_VoiceRegisterMessage_2eproto
