// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: VoiceRegisterMessage.proto
#ifndef GRPC_VoiceRegisterMessage_2eproto__INCLUDED
#define GRPC_VoiceRegisterMessage_2eproto__INCLUDED

#include "VoiceRegisterMessage.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

class RegisterMsgService final {
 public:
  static constexpr char const* service_full_name() {
    return "RegisterMsgService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status registerVoice(::grpc::ClientContext* context, const ::VoiceRegisterRequestMsg& request, ::VoiceRegisterResponseMsg* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::VoiceRegisterResponseMsg>> AsyncregisterVoice(::grpc::ClientContext* context, const ::VoiceRegisterRequestMsg& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::VoiceRegisterResponseMsg>>(AsyncregisterVoiceRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::VoiceRegisterResponseMsg>> PrepareAsyncregisterVoice(::grpc::ClientContext* context, const ::VoiceRegisterRequestMsg& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::VoiceRegisterResponseMsg>>(PrepareAsyncregisterVoiceRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void registerVoice(::grpc::ClientContext* context, const ::VoiceRegisterRequestMsg* request, ::VoiceRegisterResponseMsg* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void registerVoice(::grpc::ClientContext* context, const ::VoiceRegisterRequestMsg* request, ::VoiceRegisterResponseMsg* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void registerVoice(::grpc::ClientContext* context, const ::VoiceRegisterRequestMsg* request, ::VoiceRegisterResponseMsg* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::VoiceRegisterResponseMsg>* AsyncregisterVoiceRaw(::grpc::ClientContext* context, const ::VoiceRegisterRequestMsg& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::VoiceRegisterResponseMsg>* PrepareAsyncregisterVoiceRaw(::grpc::ClientContext* context, const ::VoiceRegisterRequestMsg& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status registerVoice(::grpc::ClientContext* context, const ::VoiceRegisterRequestMsg& request, ::VoiceRegisterResponseMsg* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::VoiceRegisterResponseMsg>> AsyncregisterVoice(::grpc::ClientContext* context, const ::VoiceRegisterRequestMsg& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::VoiceRegisterResponseMsg>>(AsyncregisterVoiceRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::VoiceRegisterResponseMsg>> PrepareAsyncregisterVoice(::grpc::ClientContext* context, const ::VoiceRegisterRequestMsg& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::VoiceRegisterResponseMsg>>(PrepareAsyncregisterVoiceRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void registerVoice(::grpc::ClientContext* context, const ::VoiceRegisterRequestMsg* request, ::VoiceRegisterResponseMsg* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void registerVoice(::grpc::ClientContext* context, const ::VoiceRegisterRequestMsg* request, ::VoiceRegisterResponseMsg* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void registerVoice(::grpc::ClientContext* context, const ::VoiceRegisterRequestMsg* request, ::VoiceRegisterResponseMsg* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::VoiceRegisterResponseMsg>* AsyncregisterVoiceRaw(::grpc::ClientContext* context, const ::VoiceRegisterRequestMsg& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::VoiceRegisterResponseMsg>* PrepareAsyncregisterVoiceRaw(::grpc::ClientContext* context, const ::VoiceRegisterRequestMsg& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_registerVoice_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status registerVoice(::grpc::ServerContext* context, const ::VoiceRegisterRequestMsg* request, ::VoiceRegisterResponseMsg* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_registerVoice : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_registerVoice() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_registerVoice() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status registerVoice(::grpc::ServerContext* /*context*/, const ::VoiceRegisterRequestMsg* /*request*/, ::VoiceRegisterResponseMsg* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestregisterVoice(::grpc::ServerContext* context, ::VoiceRegisterRequestMsg* request, ::grpc::ServerAsyncResponseWriter< ::VoiceRegisterResponseMsg>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_registerVoice<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_registerVoice : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_registerVoice() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::VoiceRegisterRequestMsg, ::VoiceRegisterResponseMsg>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::VoiceRegisterRequestMsg* request, ::VoiceRegisterResponseMsg* response) { return this->registerVoice(context, request, response); }));}
    void SetMessageAllocatorFor_registerVoice(
        ::grpc::experimental::MessageAllocator< ::VoiceRegisterRequestMsg, ::VoiceRegisterResponseMsg>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(0);
    #endif
      static_cast<::grpc::internal::CallbackUnaryHandler< ::VoiceRegisterRequestMsg, ::VoiceRegisterResponseMsg>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_registerVoice() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status registerVoice(::grpc::ServerContext* /*context*/, const ::VoiceRegisterRequestMsg* /*request*/, ::VoiceRegisterResponseMsg* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* registerVoice(
      ::grpc::CallbackServerContext* /*context*/, const ::VoiceRegisterRequestMsg* /*request*/, ::VoiceRegisterResponseMsg* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* registerVoice(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::VoiceRegisterRequestMsg* /*request*/, ::VoiceRegisterResponseMsg* /*response*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_registerVoice<Service > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_registerVoice<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_registerVoice : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_registerVoice() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_registerVoice() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status registerVoice(::grpc::ServerContext* /*context*/, const ::VoiceRegisterRequestMsg* /*request*/, ::VoiceRegisterResponseMsg* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_registerVoice : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_registerVoice() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_registerVoice() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status registerVoice(::grpc::ServerContext* /*context*/, const ::VoiceRegisterRequestMsg* /*request*/, ::VoiceRegisterResponseMsg* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestregisterVoice(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_registerVoice : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_registerVoice() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->registerVoice(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_registerVoice() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status registerVoice(::grpc::ServerContext* /*context*/, const ::VoiceRegisterRequestMsg* /*request*/, ::VoiceRegisterResponseMsg* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* registerVoice(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* registerVoice(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_registerVoice : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_registerVoice() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::VoiceRegisterRequestMsg, ::VoiceRegisterResponseMsg>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::VoiceRegisterRequestMsg, ::VoiceRegisterResponseMsg>* streamer) {
                       return this->StreamedregisterVoice(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_registerVoice() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status registerVoice(::grpc::ServerContext* /*context*/, const ::VoiceRegisterRequestMsg* /*request*/, ::VoiceRegisterResponseMsg* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedregisterVoice(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::VoiceRegisterRequestMsg,::VoiceRegisterResponseMsg>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_registerVoice<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_registerVoice<Service > StreamedService;
};


#endif  // GRPC_VoiceRegisterMessage_2eproto__INCLUDED
